In [7]:
import pandas as pd
dataset = pd.read_csv('../../data/engine_data_normal.csv')
df = dataset.iloc[:, [1, 2, 3, 4, 5, 6, 7, 8, 16]].head().append(dataset.iloc[:, [1, 2, 3, 4, 5, 6, 7, 8, 16]].tail())
df

    month  air_temp  noise  epr   egt    ff     n1     n2  failure_prob
0       1        -3    130   50  1300  5000  12000   1000             0
1       2       -11    130   48  1317  5013  12050  10062             0
2       3        -8    130   48  1332  5020  12089  10082             0
3       4       -11    130   48  1339  5027  12125  10120             0
4       5        -3    131   49  1352  5037  12152  10160             0
55     56       -15    141   51  1913  5500  13926  11935            85
56     57       -13    141   52  1920  5508  13970  11986            91
57     58        -7    141   52  1934  5513  14020  11999            97
58     59        -9    141   50  1947  5525  14039  12060           100
59     60        -2    142   52  1951  5536  14065  12096           100