In [6]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.externals import joblib

In [7]:
# Importing the dataset
dataset = pd.read_csv('../../data/engine_data_error_egt.csv')
X = dataset.iloc[:, 1:9]
y = dataset.iloc[:, [16]]

In [8]:
# Splitting the dataset manually
X_train = X.iloc[0:4500, :]
X_test = X.iloc[4500:6000, :]

y_train = y.iloc[0:4500, :].values
y_test = y.iloc[4500:6000, :].values

In [9]:
# Encoding categorical data
X_train_encode = X_train.values
X_test_encode = X_test.values

labelencoder_X_train = LabelEncoder()
X_train_encode[:, 0] = labelencoder_X_train.fit_transform(X_train_encode[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X_train_encode = onehotencoder.fit_transform(X_train_encode).toarray()

labelencoder_X_test = LabelEncoder()
X_test_encode[:, 0] = labelencoder_X_test.fit_transform(X_test_encode[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X_test_encode = onehotencoder.fit_transform(X_test_encode).toarray()

In [10]:
# Avoiding dummy variable trap
categories = [0]
dummies = []
dummies_sum = 0

for category in categories:
    dummies_sum += (dataset.iloc[:, category].unique().size) * category
    dummies.append(dummies_sum)

X_train_encode = np.delete(X_train_encode, dummies, 1)
X_test_encode = np.delete(X_test_encode, dummies, 1)

In [11]:
# Fitting Multiple Linear Regression to the Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train_encode, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
# Predicting the Test Set results
y_pred = regressor.predict(X_test_encode)
y_pred[y_pred > 100] = 100
y_pred = y_pred.ravel()
y_p = np.abs(y_pred) / 100

In [47]:
dataset[dataset['normal'] == False].head()

,engine,month,air_temp,noise,epr,egt,ff,n1,n2,noise_n,epr_n,egt_n,ff_n,n1_n,n2_n,normal,failure_prob
14,1,15,-7,133,50,1760,5134,12519,10523,True,True,False,True,True,True,False,1
15,1,16,0,133,50,1770,5142,12526,10528,True,True,False,True,True,True,False,2
16,1,17,-3,133,48,1780,5147,12567,10568,True,True,False,True,True,True,False,3
17,1,18,-14,133,50,1793,5153,12596,10617,True,True,False,True,True,True,False,4
18,1,19,-14,133,49,1799,5166,12654,10650,True,True,False,True,True,True,False,5

In [49]:
#Final Output
normal_false = dataset[dataset['normal'] == False].head(46)
normal_false

,engine,month,air_temp,noise,epr,egt,ff,n1,n2,noise_n,epr_n,egt_n,ff_n,n1_n,n2_n,normal,failure_prob
14,1,15,-7,133,50,1760,5134,12519,10523,True,True,False,True,True,True,False,1
15,1,16,0,133,50,1770,5142,12526,10528,True,True,False,True,True,True,False,2
16,1,17,-3,133,48,1780,5147,12567,10568,True,True,False,True,True,True,False,3
17,1,18,-14,133,50,1793,5153,12596,10617,True,True,False,True,True,True,False,4
18,1,19,-14,133,49,1799,5166,12654,10650,True,True,False,True,True,True,False,5
19,1,20,-2,134,50,1811,5176,12682,10666,True,True,False,True,True,True,False,6
20,1,21,-14,134,50,1825,5180,12717,10716,True,True,False,True,True,True,False,7
21,1,22,-9,134,48,1841,5189,12746,10746,True,True,False,True,True,True,False,8
22,1,23,-9,134,48,1843,5199,12776,10787,True,True,False,True,True,True,False,9
23,1,24,-14,134,48,1858,5212,12815,10821,True,True,False,True,True,True,False,10
24,1,25,-13,135,49,1865,5217,12854,10850,True,True,False,True,True,True,False,11
25,1,26,-4,135,49,1876,5231,12881,10900,True,True,False,True,True,True,False,12
26,1,27,-3,135,48,1887,5234,12921,10940,True,True,False,True,True,True,False,13
27,1,28,-6,135,50,1898,5244,12949,10976,True,True,False,True,True,True,False,14
28,1,29,-8,135,49,1911,5257,13012,11005,True,True,False,True,True,True,False,15
29,1,30,-13,136,49,1928,5265,13017,11035,True,True,False,True,True,True,False,16
30,1,31,-3,136,48,1940,5275,13070,11080,True,True,False,True,True,True,False,17
31,1,32,-15,136,50,1945,5279,13116,11092,True,True,False,True,True,True,False,18
32,1,33,-8,136,48,1959,5292,13141,11132,True,True,False,True,True,True,False,19
33,1,34,-3,136,49,1965,5300,13158,11180,True,True,False,True,True,True,False,20
34,1,35,-1,137,50,1979,5306,13222,11218,True,True,False,True,True,True,False,21
35,1,36,-6,137,48,1987,5322,13228,11257,True,True,False,True,True,True,False,22
36,1,37,-5,137,51,1997,5328,13287,11291,True,False,False,True,True,True,False,24
37,1,38,-15,137,49,2013,5338,13300,11328,True,True,False,True,True,True,False,25
38,1,39,-13,137,50,2019,5343,13363,11331,True,True,False,True,True,True,False,26
39,1,40,-13,138,49,2034,5352,13395,11368,False,True,False,False,True,True,False,29
40,1,41,0,138,49,2042,5368,13400,11413,False,True,False,False,True,True,False,32
41,1,42,-6,138,52,2055,5370,13460,11463,False,False,False,False,True,True,False,36
42,1,43,-13,138,51,2068,5384,13494,11475,False,False,False,False,True,True,False,40
43,1,44,-4,138,52,2083,5391,13537,11535,False,False,False,False,False,False,False,46
44,1,45,-2,139,51,2088,5401,13567,11571,False,False,False,False,False,False,False,52
45,1,46,-2,139,52,2097,5406,13597,11608,False,False,False,False,False,False,False,58
46,1,47,-14,139,50,2113,5418,13621,11614,False,True,False,False,False,False,False,63
47,1,48,-11,139,50,2119,5428,13651,11656,False,True,False,False,False,False,False,68
48,1,49,-8,139,49,2128,5437,13699,11698,False,True,False,False,False,False,False,73
49,1,50,-11,140,50,2143,5443,13746,11745,False,True,False,False,False,False,False,78
50,1,51,-13,140,50,2152,5457,13783,11758,False,True,False,False,False,False,False,83
51,1,52,-6,140,50,2168,5463,13815,11787,False,True,False,False,False,False,False,88
52,1,53,-13,140,49,2180,5471,13826,11834,False,True,False,False,False,False,False,93
53,1,54,-15,140,50,2187,5481,13863,11857,False,True,False,False,False,False,False,98
54,1,55,-11,141,49,2194,5487,13890,11916,False,True,False,False,False,False,False,100
55,1,56,-1,141,50,2212,5498,13946,11957,False,True,False,False,False,False,False,100
56,1,57,-9,141,49,2218,5506,13981,11992,False,True,False,False,False,False,False,100
57,1,58,-7,141,50,2235,5521,14025,12004,False,True,False,False,False,False,False,100
58,1,59,-14,141,49,2245,5529,14042,12034,False,True,False,False,False,False,False,100
59,1,60,-7,142,51,2256,5535,14082,12079,False,False,False,False,False,False,False,100

In [50]:
all_normal_columns = normal_false[['noise_n', 'epr_n', 'egt_n', 'ff_n', 'n1_n', 'n2_n']].columns
all_normal_columns = list(all_normal_columns.values)
cols = normal_false[all_normal_columns].columns[(normal_false[all_normal_columns] == False).iloc[0]]

In [52]:
for i in cols:
    print(i, normal_false[i[:-2]])

egt_n 14    1760
15    1770
16    1780
17    1793
18    1799
19    1811
20    1825
21    1841
22    1843
23    1858
24    1865
25    1876
26    1887
27    1898
28    1911
29    1928
30    1940
31    1945
32    1959
33    1965
34    1979
35    1987
36    1997
37    2013
38    2019
39    2034
40    2042
41    2055
42    2068
43    2083
44    2088
45    2097
46    2113
47    2119
48    2128
49    2143
50    2152
51    2168
52    2180
53    2187
54    2194
55    2212
56    2218
57    2235
58    2245
59    2256
Name: egt, dtype: int64

In [ ]:
## Saving the model
#joblib.dump(regressor, 'multiple_reg_error.pkl')
#
## Visualising the results
#
## First Observation
#plt.plot(X_test['month'][0:60], y_normal, color = 'red')
#plt.plot(X_test['month'][0:60], y_p[0:60], color = 'blue')
#plt.xticks(np.arange(0, 61, 2))
#plt.yticks(np.arange(0, 1.05, 0.05))
#plt.title('Age (in months) vs Probability of Failure')
#plt.xlabel('Age (in months)')
#plt.ylabel('Probability of Failure')
#plt.show()