In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.externals import joblib

In [2]:
# Importing the dataset
dataset = pd.read_csv('../../data/engine_data_error_egt.csv')
X = dataset.iloc[:, 1:9]
y = dataset.iloc[:, [16]]

In [3]:
# Splitting the dataset manually
X_train = X.iloc[0:4500, :]
X_test = X.iloc[4500:6000, :]

y_train = y.iloc[0:4500, :].values
y_test = y.iloc[4500:6000, :].values

In [4]:
# Encoding categorical data
X_train_encode = X_train.values
X_test_encode = X_test.values

labelencoder_X_train = LabelEncoder()
X_train_encode[:, 0] = labelencoder_X_train.fit_transform(X_train_encode[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X_train_encode = onehotencoder.fit_transform(X_train_encode).toarray()

labelencoder_X_test = LabelEncoder()
X_test_encode[:, 0] = labelencoder_X_test.fit_transform(X_test_encode[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X_test_encode = onehotencoder.fit_transform(X_test_encode).toarray()

In [5]:
# Avoiding dummy variable trap
categories = [0]
dummies = []
dummies_sum = 0

for category in categories:
    dummies_sum += (dataset.iloc[:, category].unique().size) * category
    dummies.append(dummies_sum)

X_train_encode = np.delete(X_train_encode, dummies, 1)
X_test_encode = np.delete(X_test_encode, dummies, 1)

In [6]:
# Fitting Multiple Linear Regression to the Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train_encode, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
# Predicting the Test Set results
y_pred = regressor.predict(X_test_encode)
y_pred[y_pred > 100] = 100
y_pred = y_pred.ravel()
y_p = np.abs(y_pred) / 100

In [8]:
dataset[dataset['normal'] == False].head()

,engine,month,air_temp,noise,epr,egt,ff,n1,n2,noise_n,epr_n,egt_n,ff_n,n1_n,n2_n,normal,failure_prob
13,1,14,-10,132,49,1753,5125,12462,10467,True,True,False,True,True,True,False,3
14,1,15,-5,133,49,1760,5132,12506,10516,True,True,False,True,True,True,False,6
15,1,16,-9,133,48,1767,5138,12558,10529,True,True,False,True,True,True,False,9
16,1,17,-1,133,48,1784,5145,12594,10582,True,True,False,True,True,True,False,12
17,1,18,-11,133,50,1788,5158,12628,10623,True,True,False,True,True,True,False,15

In [9]:
engine1 = dataset[dataset['engine'] == 1]

In [10]:
#Final Output
normal_false = engine1[engine1['normal'] == False]
normal_false

,engine,month,air_temp,noise,epr,egt,ff,n1,n2,noise_n,epr_n,egt_n,ff_n,n1_n,n2_n,normal,failure_prob
13,1,14,-10,132,49,1753,5125,12462,10467,True,True,False,True,True,True,False,3
14,1,15,-5,133,49,1760,5132,12506,10516,True,True,False,True,True,True,False,6
15,1,16,-9,133,48,1767,5138,12558,10529,True,True,False,True,True,True,False,9
16,1,17,-1,133,48,1784,5145,12594,10582,True,True,False,True,True,True,False,12
17,1,18,-11,133,50,1788,5158,12628,10623,True,True,False,True,True,True,False,15
18,1,19,-12,133,49,1800,5166,12650,10635,True,True,False,True,True,True,False,18
19,1,20,-5,134,49,1811,5178,12684,10676,True,True,False,True,True,True,False,21
20,1,21,-15,134,50,1826,5183,12700,10721,True,True,False,True,True,True,False,24
21,1,22,-14,134,49,1832,5192,12742,10750,True,True,False,True,True,True,False,27
22,1,23,-7,134,50,1850,5204,12782,10773,True,True,False,True,True,True,False,30
23,1,24,-5,134,49,1855,5211,12812,10826,True,True,False,True,True,True,False,33
24,1,25,-4,135,49,1868,5223,12845,10864,True,True,False,True,True,True,False,36
25,1,26,-2,135,49,1875,5230,12881,10903,True,True,False,True,True,True,False,39
26,1,27,0,135,50,1889,5236,12921,10940,True,True,False,True,True,True,False,42
27,1,28,-11,135,50,1904,5248,12950,10966,True,True,False,True,True,True,False,45
28,1,29,-1,135,48,1913,5255,13009,10983,True,True,False,True,True,True,False,48
29,1,30,-6,136,48,1925,5263,13029,11033,True,True,False,True,True,True,False,51
30,1,31,-15,136,48,1937,5273,13061,11059,True,True,False,True,True,True,False,54
31,1,32,-13,136,49,1951,5286,13095,11098,True,True,False,True,True,True,False,57
32,1,33,-14,136,50,1953,5294,13129,11122,True,True,False,True,True,True,False,60
33,1,34,0,136,49,1966,5304,13184,11161,True,True,False,True,True,True,False,63
34,1,35,-10,137,48,1981,5306,13222,11211,True,True,False,True,True,True,False,66
35,1,36,0,137,48,1992,5318,13233,11229,True,True,False,True,True,True,False,69
36,1,37,-8,137,49,2004,5326,13263,11270,True,True,False,True,True,True,False,72
37,1,38,-3,137,49,2007,5339,13305,11308,True,True,False,True,True,True,False,75
38,1,39,-1,137,49,2018,5346,13363,11363,True,True,False,True,True,True,False,78
39,1,40,-4,138,50,2030,5359,13395,11388,True,True,False,True,True,True,False,81
40,1,41,-13,138,50,2050,5365,13412,11421,True,True,False,True,True,True,False,84
41,1,42,0,138,52,2054,5370,13465,11436,True,True,False,True,True,True,False,87
42,1,43,-6,138,50,2070,5378,13502,11504,True,True,False,True,True,True,False,90
43,1,44,-1,138,50,2081,5389,13517,11512,True,True,False,True,True,True,False,93
44,1,45,-9,139,50,2085,5404,13558,11543,True,True,False,True,True,True,False,96
45,1,46,-1,139,52,2105,5407,13587,11605,True,True,False,True,True,True,False,99
46,1,47,-8,139,49,2111,5421,13642,11629,True,True,False,True,True,True,False,100
47,1,48,-2,139,50,2120,5425,13676,11664,True,True,False,True,True,True,False,100
48,1,49,-4,139,52,2137,5437,13693,11693,True,True,False,True,True,True,False,100
49,1,50,-11,140,51,2146,5447,13734,11738,True,True,False,True,True,True,False,100
50,1,51,-15,140,49,2159,5454,13754,11776,True,True,False,True,True,True,False,100
51,1,52,-4,140,50,2166,5461,13786,11811,True,True,False,True,True,True,False,100
52,1,53,-6,140,52,2181,5469,13822,11822,True,True,False,True,True,True,False,100
53,1,54,-9,140,50,2183,5479,13878,11880,True,True,False,True,True,True,False,100
54,1,55,-12,141,51,2201,5491,13908,11917,True,True,False,True,True,True,False,100
55,1,56,-1,141,50,2207,5498,13936,11952,True,True,False,True,True,True,False,100
56,1,57,-6,141,50,2220,5505,13993,11968,True,True,False,True,True,True,False,100
57,1,58,-14,141,50,2230,5520,14027,12017,True,True,False,True,True,True,False,100
58,1,59,-11,141,51,2240,5527,14042,12045,True,True,False,True,True,True,False,100
59,1,60,-9,142,49,2250,5539,14072,12091,True,True,False,True,True,True,False,100

In [11]:
failure_start = normal_false.head(1)
failure_final = normal_false[normal_false['failure_prob'] == 100].head(1)

In [12]:
all_normal_columns = normal_false[['noise_n', 'epr_n', 'egt_n', 'ff_n', 'n1_n', 'n2_n']].columns
all_normal_columns = list(all_normal_columns.values)
cols = normal_false[all_normal_columns].columns[(normal_false[all_normal_columns] == False).iloc[0]]

In [13]:
failures_start = []
for i in list(cols):
    print(i, failure_start[i[:-2]])
    failures_start.append(failure_start[[list(cols)[0][:-2], 'month']])

failures_start

egt_n 13    1753
Name: egt, dtype: int64

[     egt  month
 13  1753     14]

In [14]:
failures_final = []
for i in list(cols):
    print(i, failure_final[i[:-2]])
    failures_final.append(failure_final[[list(cols)[0][:-2], 'month']])
    
failures_final

egt_n 46    2111
Name: egt, dtype: int64

[     egt  month
 46  2111     47]

In [15]:
## Saving the model
#joblib.dump(regressor, 'multiple_reg_error.pkl')
#
## Visualising the results
#
## First Observation
#plt.plot(X_test['month'][0:60], y_normal, color = 'red')
#plt.plot(X_test['month'][0:60], y_p[0:60], color = 'blue')
#plt.xticks(np.arange(0, 61, 2))
#plt.yticks(np.arange(0, 1.05, 0.05))
#plt.title('Age (in months) vs Probability of Failure')
#plt.xlabel('Age (in months)')
#plt.ylabel('Probability of Failure')
#plt.show()